{% set name = "openmm-atmmetaforce-plugin" %}
{% set version = "0.3.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Gallicchio-Lab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a6e96971d9d235a821653513123d3bd9876ad2bf540700e42327f668e96502ab

build:
  number: 2
  skip: true  # [(cuda_compiler_version in (undefined, 'None') and (linux64 or win))]
  # Skip broken OpenMM packages for Windows
  skip: true  # [win and py==38]
  skip: true  # [win and py==310]
  skip: true  # [win and py==311]
  rpaths:
    - lib/
    - lib/plugins/
  run_exports:
    # TODO: Relax max_pin at version 1.0 / stable API
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 or win64]
    - make  # [unix]
    - ninja  # [win]
    - cmake
    - swig

  host:
    - openmm
    - python
    - pip
    - setuptools

  run:
    # openmm package is missing a run_export as of 9 June 2022
    - {{ pin_compatible('openmm', min_pin='x.x', max_pin='x.x') }}
    - python

test:
  imports:
    - atmmetaforce

about:
  home: https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin.git
  license: LGPL-2.0-only
  license_family: LGPL
  license_file:
    - LICENSE
  summary: The Alchemical Transfer Method Plugin for OpenMM
  description: |
    This plugin implements the Alchemical Transfer Potential (ATM) for the calculation
    of absolute and relative binding free energies of molecular complexes
    in OpenMM, a high performance toolkit for molecular simulation.
  doc_url: https://github.com/Gallicchio-Lab/async_re-openmm/tree/master/examples
  dev_url: https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin.git

extra:
  recipe-maintainers:
    - egallicc
